
*** MOST IMPORTANT ANCHORS FOR SETTING CIRCADIAN RYTHM
Your body has an internal compass, Think of a it as  a songs rythm, and your objective is to follow it as close as possible. The cool thing is that if you work hard on it, you actually can dictate the rythm by yourself, not the other way around it. The following three elements are the most important anchors that will regulate your compass and help your sleep schedule:
1. LIGHT EXPOSURE
2. EXHAUSTION
3. EATING SCHEDULE

   In reality, any habit that you do every day at the same time of the day will help, it sends a signal that tells your body what time it is and will help readjusting your clock. As more and more powerful signals you give to your body, the more and more accurate your clock will get and the better youll sleep.

*** QUICK READ WITH STEPS AND TRICKS FOR IMPROVING SLEEP

1. Dont try to shift sleep schedule by going to sleep earlier, instead wake up earlier, even if that supposes sleep deprivation for a couple days.
2. Get 10 min of direct sunlight exposure right after waking up.
3. Weekdays and weekends MUST have the same sleep schedule. DO NOT go to sleep later on weekends. It will screw up your sleep schedule for no reason at all. Thats pretty stupid. Seriously dont do it.
4. Make yourself as exhausted as possible during the day so you have the need to go to sleep earlier.
5. Try to get as much exposure to light(s) early on the day and avoid them later on, if not possible, try to dim and warm them as much as you can.
6. Stop working, exercising and eating at least 2 hours before sleep time.
7. Start reading 1 hour before your sleep time.
19. Set up an alarm for waking up but more importantly set up another for sleeping. I personally have it 1h before my bed time, so I know its time for winding down and calm reading.
8. Avoid caffeine alcohol, and nicotine at any cost.
9. Avoid medicaments that affect sleep.
10. Dont take naps after 15:00.
11. Take a cold bath after waking up and a hot one before bed.
12. Make your bedroom as dark as possible.
13. Take anything in your bedroom that might distract you from sleep (noises, lights...).
14. Take any smart devices out of your bedroom.
15. Dont lie in bed awake, if you find yourself still awake after staying in bed for 20 mins or more, or you start to get anxious, get up and do some relaxing activity until you feel sleepy. The anxiety of not being able to sleep can make it harder to fall asleep.
16. Ritualize your nightly routine for setting the mood to sleep.
17. Practice meditation during the day.
18. Sit alone with your thoughts for some time in the day. Sometimes the problem people have is that they never sit to JUST think during the day. And all the problems and worries they have accumulated will start creeping in in the only moment they are truly by themselves. At night. While trying to sleep.
19. Practice yoga nidra before sleep, after waking up in the middle of the night, or after a suboptimal (less than 7 hours of sleep time) night of sleep.
20. Use blue filters in electronic screens, get blue filter glasses.
21. The bed (and the bedroom ideally ) is for sleep and sex ONLY.
22. A cool bedroom is better than a hot bedroom, the ideal temperature for sleep is around 18 to 20 degrees.
23. Drown out any noise outside. Try out earplugs or white noise.
24. Try calming scents, light smells such as lavender may induce a calmer state of mind and help cultivate a positive space for sleep.
25. Invest in a good mattress.
26. Get a weighted blanket (10% of your BW).
27. Use a light alarm. I personally use a digital plug-in timer with a lamp attached (the mechanical ones make annoying noises do not use them).
28. Aim for 9 hours of scheduled sleep each night, I personally feel that it takes pressure off from my chest knowing that its okay if I dont sleep them all, and makes a 1 hour safety buffer if anything happens. Ex. if I end up having to stay up half hour late or a bit more for whatever reason, It does not stress me knowing that I still have a lot sleep time left before the critical < 8.
29. Sleep journal.
30. Prevent snoring (side sleeping, CPAP, mouthpieces, ?mouth tape?(idk it may be dangerous), nose canal openers).
31. Suspicious of having sleep apnea? consult with your doctor ASAP.


*** RESOURCES
https://www.sleepfoundation.org/

https://www.goodreads.com/book/show/34466963-why-we-sleep

https://www.goodreads.com/book/show/53641433-sleep-through-insomnia

https://play.google.com/store/apps/details?id=gov.va.mobilehealth.ncptsd.cbti&hl=en
